apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base
  - rollout/api-rollout.yaml
  - services/preview-service.yaml
  - policy/api-pdb.yaml

patches:
  - path: patches/delete-api-deployment.yaml
