apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: everything-backend-secret-store
  labels:
    app.kubernetes.io/name: everything-backend-api
    app.kubernetes.io/component: secret-store
spec:
  provider:
    vault:
      server: https://vault.everything-backend.svc:8200
      path: secret
      version: v2
      auth:
        tokenSecretRef:
          name: external-secrets-vault-token
          key: token
          namespace: external-secrets
