apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  OTEL_METRICS_ENABLED: "true"
  OTEL_TRACING_ENABLED: "true"
  OTEL_LOGS_ENABLED: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317
  OTEL_EXPORTER_OTLP_INSECURE: "true"
