apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: secure-observable

resources:
  - ../../base
  - configmaps
  - deployments
  - services

patches:
  - path: patches/app-config-otel.yaml
