apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../observability-base
  - pvc

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: tempo-config
    behavior: replace
    files:
      - config/tempo.yaml
  - name: loki-config
    behavior: replace
    files:
      - config/loki.yaml

patches:
  - path: patches/persistence.yaml
  - path: patches/resources.yaml
