apiVersion: v1
kind: Service
metadata:
  name: mimir
  labels:
    app.kubernetes.io/name: mimir
    app.kubernetes.io/component: observability
spec:
  selector:
    app.kubernetes.io/name: mimir
  ports:
    - name: http
      port: 9009
      targetPort: http
