apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: everything-backend-api
  labels:
    app.kubernetes.io/name: everything-backend-api
    app.kubernetes.io/component: ingress
spec:
  ingressClassName: nginx
  rules:
    - host: everything-backend.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: everything-backend-api
                port:
                  number: 8080
